package com.neo4j.loopy.config;

import com.neo4j.loopy.LoopyConfig;
import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.Properties;

/**
 * Configuration Manager for Loopy
 * Handles configuration file operations, validation, and conversion
 */
public class ConfigManager {
    
    public static final String DEFAULT_CONFIG_TEMPLATE = """
        # Loopy Configuration File
        # Neo4j Load Testing Configuration
        
        # Neo4j Connection Settings
        neo4j.uri=bolt://localhost:7687
        neo4j.username=neo4j
        neo4j.password=password
        
        # Load Testing Parameters
        threads=4
        duration.seconds=300
        write.ratio=0.7
        batch.size=100
        
        # Data Configuration
        node.labels=Person,Company
        relationship.types=WORKS_FOR,KNOWS
        property.size.bytes=100
        
        # Reporting Configuration
        report.interval.seconds=10
        csv.logging.enabled=false
        csv.logging.file=loopy-results.csv
        """;
    
    /**
     * Generate a default configuration file
     */
    public boolean generateDefaultConfig(String filePath) {
        try {
            Path path = Paths.get(filePath);
            
            // Create directories if they don't exist
            Path parent = path.getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            
            // Write default configuration
            try (BufferedWriter writer = Files.newBufferedWriter(path)) {
                writer.write("# Generated by Loopy Config Manager on " + LocalDateTime.now() + "\n");
                writer.write(DEFAULT_CONFIG_TEMPLATE);
            }
            
            return true;
            
        } catch (IOException e) {
            System.err.println("Failed to generate default config: " + e.getMessage());
            return false;
        }
    }
    
    /**
     * Validate a configuration file
     */
    public ValidationResult validateConfig(String filePath) {
        ValidationResult result = new ValidationResult();
        
        try {
            // Check if file exists
            if (!Files.exists(Paths.get(filePath))) {
                result.addError("Configuration file does not exist: " + filePath);
                return result;
            }
            
            // Load and validate configuration
            LoopyConfig config = new LoopyConfig(filePath);
            
            // Validate using LoopyConfig's validation methods
            try {
                config.validate();
                result.setValid(true);
            } catch (IllegalArgumentException e) {
                result.addError("Configuration validation failed: " + e.getMessage());
            }
            
            // Additional validations
            validateAdvanced(config, result);
            
        } catch (Exception e) {
            result.addError("Failed to load configuration: " + e.getMessage());
        }
        
        return result;
    }
    
    private void validateAdvanced(LoopyConfig config, ValidationResult result) {
        // Check for reasonable values
        if (config.getThreads() > Runtime.getRuntime().availableProcessors() * 2) {
            result.addWarning("Thread count (" + config.getThreads() + 
                ") is high compared to available processors (" + 
                Runtime.getRuntime().availableProcessors() + ")");
        }
        
        if (config.getDurationSeconds() > 3600) {
            result.addWarning("Long test duration (" + config.getDurationSeconds() + 
                " seconds). Consider shorter tests for initial validation.");
        }
        
        if (config.getBatchSize() > 1000) {
            result.addWarning("Large batch size (" + config.getBatchSize() + 
                ") may cause memory issues with large datasets.");
        }
        
        // Check file paths
        if (config.isCsvLoggingEnabled() && config.getCsvLoggingFile() != null) {
            Path csvPath = Paths.get(config.getCsvLoggingFile());
            Path parent = csvPath.getParent();
            if (parent != null && !Files.exists(parent)) {
                try {
                    Files.createDirectories(parent);
                    result.addInfo("Created directory for CSV output: " + parent);
                } catch (IOException e) {
                    result.addWarning("Cannot create directory for CSV output: " + parent);
                }
            }
        }
    }
    
    /**
     * Display current effective configuration
     */
    public void showConfig(String filePath) {
        try {
            LoopyConfig config = new LoopyConfig(filePath);
            
            System.out.println("\u001B[36m=== Loopy Configuration ===\u001B[0m");
            System.out.println("Configuration file: " + filePath);
            System.out.println();
            
            System.out.println("\u001B[33mNeo4j Connection:\u001B[0m");
            System.out.println("  URI: " + config.getNeo4jUri());
            System.out.println("  Username: " + config.getNeo4jUsername());
            System.out.println("  Password: " + (config.getNeo4jPassword().isEmpty() ? "not set" : "***"));
            System.out.println();
            
            System.out.println("\u001B[33mLoad Testing:\u001B[0m");
            System.out.println("  Threads: " + config.getThreads());
            System.out.println("  Duration: " + config.getDurationSeconds() + " seconds (" + 
                (config.getDurationSeconds() / 60) + " minutes)");
            System.out.println("  Write Ratio: " + (config.getWriteRatio() * 100) + "%");
            System.out.println("  Batch Size: " + config.getBatchSize());
            System.out.println();
            
            System.out.println("\u001B[33mData Configuration:\u001B[0m");
            System.out.println("  Node Labels: " + config.getNodeLabels());
            System.out.println("  Relationship Types: " + config.getRelationshipTypes());
            System.out.println("  Property Size: " + config.getPropertySizeBytes() + " bytes");
            System.out.println();
            
            System.out.println("\u001B[33mReporting:\u001B[0m");
            System.out.println("  Report Interval: " + config.getReportIntervalSeconds() + " seconds");
            System.out.println("  CSV Logging: " + (config.isCsvLoggingEnabled() ? "enabled" : "disabled"));
            if (config.isCsvLoggingEnabled()) {
                System.out.println("  CSV File: " + config.getCsvLoggingFile());
            }
            
        } catch (Exception e) {
            System.err.println("\u001B[31mFailed to load configuration: " + e.getMessage() + "\u001B[0m");
        }
    }
    
    /**
     * Open configuration file in default editor
     */
    public boolean editConfig(String filePath) {
        try {
            Path path = Paths.get(filePath);
            
            // Create file if it doesn't exist
            if (!Files.exists(path)) {
                System.out.println("Configuration file doesn't exist. Creating default configuration...");
                if (!generateDefaultConfig(filePath)) {
                    return false;
                }
            }
            
            // Try to open with various editors
            String os = System.getProperty("os.name").toLowerCase();
            ProcessBuilder pb;
            
            if (os.contains("mac")) {
                pb = new ProcessBuilder("open", "-t", filePath);
            } else if (os.contains("win")) {
                pb = new ProcessBuilder("notepad", filePath);
            } else {
                // Linux/Unix - try common editors
                String[] editors = {"nano", "vim", "gedit", "kate"};
                String editor = System.getenv("EDITOR");
                
                if (editor != null) {
                    pb = new ProcessBuilder(editor, filePath);
                } else {
                    // Find first available editor
                    editor = findAvailableEditor(editors);
                    if (editor == null) {
                        System.err.println("No suitable editor found. Set EDITOR environment variable or install nano/vim.");
                        return false;
                    }
                    pb = new ProcessBuilder(editor, filePath);
                }
            }
            
            System.out.println("Opening configuration file in editor: " + filePath);
            Process process = pb.start();
            
            // For terminal editors, wait for completion
            if (os.contains("nix") || os.contains("nux")) {
                process.waitFor();
            }
            
            return true;
            
        } catch (Exception e) {
            System.err.println("Failed to open editor: " + e.getMessage());
            return false;
        }
    }
    
    private String findAvailableEditor(String[] editors) {
        for (String editor : editors) {
            try {
                Process process = new ProcessBuilder("which", editor).start();
                process.waitFor();
                if (process.exitValue() == 0) {
                    return editor;
                }
            } catch (Exception e) {
                // Continue to next editor
            }
        }
        return null;
    }
    
    /**
     * Configuration validation result
     */
    public static class ValidationResult {
        private boolean valid = false;
        private StringBuilder errors = new StringBuilder();
        private StringBuilder warnings = new StringBuilder();
        private StringBuilder info = new StringBuilder();
        
        public boolean isValid() { return valid; }
        public void setValid(boolean valid) { this.valid = valid; }
        
        public void addError(String error) {
            if (errors.length() > 0) errors.append("\n");
            errors.append("ERROR: ").append(error);
        }
        
        public void addWarning(String warning) {
            if (warnings.length() > 0) warnings.append("\n");
            warnings.append("WARNING: ").append(warning);
        }
        
        public void addInfo(String info) {
            if (this.info.length() > 0) this.info.append("\n");
            this.info.append("INFO: ").append(info);
        }
        
        public String getErrors() { return errors.toString(); }
        public String getWarnings() { return warnings.toString(); }
        public String getInfo() { return this.info.toString(); }
        
        public boolean hasErrors() { return errors.length() > 0; }
        public boolean hasWarnings() { return warnings.length() > 0; }
        public boolean hasInfo() { return info.length() > 0; }
    }
}